//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aegon
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpiHeader_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MpiHeader_Test()
        {
            this.MpiReturns_Test = new HashSet<MpiReturns_Test>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string HCAUniverse { get; set; }
        public string Index { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MpiReturns_Test> MpiReturns_Test { get; set; }
    }
}
